# Generated by Django 2.2.13 on 2020-08-17 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import trivia_runner.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trivia_builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TriviaSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(default=trivia_runner.models.gen_session_code, editable=False, max_length=6, unique=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_question_index', models.IntegerField(default=0)),
                ('session_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_master', to=settings.AUTH_USER_MODEL)),
                ('trivia_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia_builder.TriviaQuiz')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreCardAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=500)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia_builder.TriviaQuestion')),
                ('score_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia_runner.ScoreCard')),
            ],
        ),
        migrations.AddField(
            model_name='scorecard',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoredeck', to='trivia_runner.TriviaSession'),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default='', max_length=24)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('score_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trivia_runner.ScoreCard')),
            ],
        ),
    ]
