# Generated by Django 3.1 on 2020-09-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_runner', '0005_remove_activetriviaquiz_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='activetriviaquiz',
            name='timeout',
            field=models.IntegerField(default=30),
        ),
    ]
